In [1]:
import numpy as np

In [2]:
i2 = np.eye(2)
print(i2)

[[1. 0.]
 [0. 1.]]


In [3]:
np.savetxt("eye.txt",i2)

In [19]:
# usecols 获取指定字段的列
# unpack 分拆不同的列
c,v = np.loadtxt('data.csv', delimiter=',',usecols=(6,7),unpack=True)
print(c)
print(v)

[346.1 336.1 326.1 346.1]
[21144800. 21144800. 21144800. 21144800.]


In [20]:
#vwap = np.average(c, weights=v)
#print(vwap)
# 就是给定的weights会首先变成加和为1的形式，然后分别乘以数组c，得到的就是vwap
c = np.array([1.1,1.2,1.3,1.4])
w = np.array([2./16,2./16,2./16,10./16]) # 跟 w = np.array([2,2,2,10])是一样的
vwap = np.average(c,weights=w)
print(vwap)
print(1.1*2./16+1.2*2/16+1.3*2./16+1.4*10/16)

1.325
1.325


In [18]:
# 算数平均值
print(c.mean())

1.25


In [31]:
# 找到最大值
h,l = np.loadtxt('data.csv',delimiter=',',usecols=(4,5), unpack=True)
print(h)
print(l)
print("highest = ", np.max(h))
print("lowest = ", np.min(l))
print("spread high price", np.ptp(h))
print("spread low price", np.ptp(l))
print("中位数 ", np.median(h))
print(np.msort(h))

[333.4 355.4 344.4 366.4]
[365.53 343.53 333.53 363.53]
highest =  366.4
lowest =  333.53
spread high price 33.0
spread low price 32.0
中位数  349.9
[333.4 344.4 355.4 366.4]


In [38]:
a = np.array([1,2,3,8,9])
print(np.median(a))
a = np.array([1,2,3,4])
print(np.median(a))
N = len(a)
print((a[int(N/2)]+a[int((N-1)/2)])/2)

3.0
2.5
2.5


In [42]:
# 方差
print(np.var(a))
print(np.mean((a-a.mean())**2))

1.25
1.25


In [46]:
# 差值
a = np.array([1,3,5,4])
print(np.diff(a))
# 对数
print(np.log(a))
# 标准差
print(np.std(a))
# 筛选
print(np.where(a > 2))

[ 2  2 -1]
[0.         1.09861229 1.60943791 1.38629436]
1.479019945774904
(array([1, 2, 3]),)


In [55]:
# 日期
import datetime
def datestr2num(s):
    s = str(s, encoding = "utf-8")
    return datetime.datetime.strptime(s, "%d-%m-%Y").date().weekday()

dates, close = np.loadtxt('data.csv', 
                          delimiter=',',
                          usecols=(1,6), 
                          converters={1:datestr2num}, 
                          unpack=True)
print(dates)
print(close)

[4. 5. 6. 0.]
[346.1 336.1 326.1 346.1]
