In [1]:
import numpy as np
import sys
from matplotlib.pyplot import plot
from matplotlib.pyplot import show

In [16]:
N = 5
weights = np.ones(N)/N
print(weights)

[0.2 0.2 0.2 0.2 0.2]


In [17]:
c = np.loadtxt('data.csv',delimiter=',', usecols=(6,), unpack=True)
sma = np.convolve(weights, c)[N-1:N+1]
deviation = []
C = len(c)
print(c)
print(sma)
print(C)

[336.1  339.32 345.03 344.32 343.44 346.5  351.88 355.2  358.16 354.54
 356.85 359.18 359.9  363.13 358.3  350.56 338.61 342.62 342.88 348.16
 353.21 349.31 352.12 359.56 360.   355.36 355.76 352.47 346.67 351.99]
[341.642 343.722]
30


In [20]:
deviation = []
for i in range(N-1, C):
    if i+N < C:
        dev = c[i:i+N]
    else:
        dev = c[-N:]
    print(dev)
    averages = np.zeros(N)
    averages.fill(sma[i-N-1])
    dev = dev-averages
    dev = dev ** 2
    dev = np.sqrt(np.mean(dev))
    deviation.append(dev)
    
print(deviation)
# todo 不知道N什么意思，这个例子不做了

[343.44 346.5  351.88 355.2  358.16]
[346.5  351.88 355.2  358.16 354.54]
[351.88 355.2  358.16 354.54 356.85]
[355.2  358.16 354.54 356.85 359.18]
[358.16 354.54 356.85 359.18 359.9 ]


IndexError: index 2 is out of bounds for axis 0 with size 2