In [1]:
import numpy as np
a = np.arange(5)
print(a.dtype)


int32


In [4]:
a = np.array([0,1,2,3,4])
print(a)
print(a.shape)

[0 1 2 3 4]
(5,)


In [8]:
m = np.array([np.arange(2),np.arange(2)])
print(m)
print(m.shape)

[[0 1]
 [0 1]]
(2, 2)


In [10]:
a = np.array([[1,2],[3,4]])
print(a)
print(a[0,0])
print(a[0,1])

[[1 2]
 [3 4]]
1
2


In [13]:
print(float(42))
print(int(42))
print(bool(42))

42.0
42
True


In [15]:
a = np.array([1,2,3,4])
print(a.dtype.itemsize)

4


In [18]:
# i 整数，u 无符号整数, f 单精度浮点数, d双精度浮点数，b布尔值，D复数，S字符串，unicode字符串，void空
a = np.arange(7, dtype='d')
print(a)
print(a.dtype.itemsize)

[0. 1. 2. 3. 4. 5. 6.]
8


In [20]:
print(np.float64(52))
print(np.sctypeDict.keys())

52.0
dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 'uintp', 'P', 'long', 'l', 7, 'L', 8, 'longlong', 'q', 9, 'ulonglong', 'Q', 10, 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'bool8', 'Bool', 'b1', 'float16', 'Float16', 'f2', 'float32', 'Float32', 'f4', 'float64', 'Float64', 'f8', 'complex64', 'Complex32', 'c8', 'complex128', 'Complex64', 'c16', 'object0', 'Object0', 'bytes0', 'Bytes0', 'str0', 'Str0', 'void0', 'Void0', 'datetime64', 'Datetime64', 'M8', 'timedelta64', 'Timedelta64', 'm8', 'int32', 'Int32', 'i4', 'uint32', 'UInt32', 'u4', 'int64', 'Int64', 'i8', 'uint64', 'UInt64', 'u8', 'int16', 'Int16', 'i2', 'uint16', 'UInt16', 'u2', 'int8', 'Int8', 'i1', 'uint8', 'UInt8', 'u1', 'complex_', 'int0', 'uint0', 'single', 'csingle', 'singlecomplex', 'floa

In [24]:
t = np.dtype('Float64')
print(t.char)
print(t.type)
print(t.str)
# > 表示大端字节序
# < 表示小端字节序

d
<class 'numpy.float64'>
<f8


c:\users\xxh\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Numeric-style type codes are deprecated and will result in an error in the future.
  """Entry point for launching an IPython kernel.


In [30]:
t = np.dtype([('name',np.str,40),('numitems',np.int32),('price',np.float32)])
print(t)
print(t['name'])
itemz = np.array([('meaning of life dvd', 32, 3.14),('Butter',13,2.72)],dtype=t)
print(itemz)
print(itemz[1])

[('name', '<U40'), ('numitems', '<i4'), ('price', '<f4')]
<U40
[('meaning of life dvd', 32, 3.14) ('Butter', 13, 2.72)]
('Butter', 13, 2.72)


In [34]:
a = np.arange(9)
print(a[3:7])
print(a[:7:2])#0到7，步长为2
print(a[::-1])#翻转数组

[3 4 5 6]
[0 2 4 6]
[8 7 6 5 4 3 2 1 0]


In [41]:
b = np.arange(24).reshape(2,3,4)
print(b.shape)
print(b)
print(b[0,0,0])
print(b[:,0,0])
print(b[0,:,:])
print(b[0,...])#多个冒号用...代替
print(b[...,1])
print(b[0,1])

(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
0
[ 0 12]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  5  9]
 [13 17 21]]
[4 5 6 7]


In [47]:
print(b[0,1,::2]) # 相隔选取
print(b[...,1])
print(b[:,1]) # 所有元素的第二行
print(b[0,:,-1]) # 第一个元素的所有行的最后一列
print(b[0,::-1,-1])

[4 6]
[[ 1  5  9]
 [13 17 21]]
[[ 4  5  6  7]
 [16 17 18 19]]
[ 3  7 11]
[11  7  3]


In [49]:
print(b[::-1])

[[[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
