- ravel 展平
- flatten 创建的新的展平数组
x.shape 改变维度
transpose 转置
resize和reshape的区别

In [4]:
import numpy as np

In [8]:
b = np.arange(24).reshape((2,3,4))
print(b)
print(b.shape)
# 展平
c = b.ravel()
print(c)
print(c.shape)
# 重新申请内存保存结果
d = b.flatten()
print(d)
print(d.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)


In [9]:
d.shape = (6,4)
print(d)
print(d.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
(6, 4)


In [10]:
# 转置
e = d.transpose()
print(e)
print(e.shape)

[[ 0  4  8 12 16 20]
 [ 1  5  9 13 17 21]
 [ 2  6 10 14 18 22]
 [ 3  7 11 15 19 23]]
(4, 6)


In [12]:
# resize，直接修改数组
# reshape，重新返回一个新的数组
b = np.arange(24)
b1 = b.reshape(2,3,4)
print(b.shape)
print(b1.shape)
b.resize(2,3,4)
print(b.shape)

(24,)
(2, 3, 4)
(2, 3, 4)
