In [1]:
import numpy as np

In [2]:
a = np.arange(9).reshape(3,3)
print(a)
b = 2*a
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [5]:
# 水平组合
c = np.hstack((a,b))
print(c)
c1 = np.concatenate((a,b), axis=1)
print(c1)

[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]
[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]


In [6]:
# 垂直组合
d = np.vstack((a,b))
print(d)
d1 = np.concatenate((a,b), axis=0)
print(d1)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [7]:
# 深度组合
e = np.dstack((a,b))
print(e)

[[[ 0  0]
  [ 1  2]
  [ 2  4]]

 [[ 3  6]
  [ 4  8]
  [ 5 10]]

 [[ 6 12]
  [ 7 14]
  [ 8 16]]]


In [10]:
# 列的组合
oned = np.arange(2)
print(oned)
twice_oned = 2*oned
print(twice_oned)
f = np.column_stack((oned, twice_oned))
print(f)
f1 = np.row_stack((oned,twice_oned))
print(f1)

[0 1]
[0 2]
[[0 0]
 [1 2]]
[[0 1]
 [0 2]]
