In [1]:
import numpy as np

In [8]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
# 水平分割
b = np.hsplit(a,3)
print(b)
b = np.split(a, 3, axis=1)
print(b)

[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]
[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]


In [10]:
# 垂直分割
c = np.vsplit(a,3)
print(c)
c = np.split(a,3,axis=0)
print(c)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]
[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]


In [ ]:
# 深度分割
d = np.arange(27).reshape(3,3,3)
print(d)
d1 = np.dsplit(c,)