In [2]:
import numpy as np

In [5]:
a = np.arange(27).reshape(3,3,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [6]:
b = np.greater_equal(a[:,:,0],10)
print(b)

[[False False False]
 [False  True  True]
 [ True  True  True]]


In [7]:
print(np.where(b))

(array([1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2]))


In [12]:
# zip方法把两个数组之间的元素一个一个的打包成元组
for i,j in zip([1,2,3],[4,5,6,7,8]):
    print(i,' ',j)

1   4
2   5
3   6


In [14]:
a = {1,2,3}
b = {0,4,5}
print(a.isdisjoint(b))

True


In [4]:
# np.around() 
# -0.5和0.5 都是0 
# 1.5和2.5 都是2
print(np.around(0.2))
print(np.around(0.5))
print(np.around(0.8))
print(np.around([-0.5,0.5,1.5,2.5,3.5,4.5]))

0.0
0.0
1.0
[-0.  0.  2.  2.  4.  4.]
